### ISSUE TITLE
Handle different Alt+ modifiers

### ISSUE THREAD

**Issue by p91paul** [p91paul/gnome-shell-extensions-coverflowalttab#10]
Here's the error report received on extensions.gnome.org:
_Your extension, "Coverflow Alt-Tab" has received an error report from finalzone:_

_**What's wrong?**_
_Alt+` command switched to main windows applications._

_**What have you tried?**_
_Alt+` command should only select only opened windows from the same application_

Before fixing I want to prepare a configuration window, so that this kind of things are choosen by users.

**Comment by p91paul** [comment]
An user on extensions.gnome.org commented about this:

Can you please make it group by applications. Atleast as an option? (Alt+tab and Alt+` are one of the best features of gnome 3.0, please try it and you won't go back) That is the only think that keep me from using this extension. By the way, the icon overlay is awesome.

And he replied to himself:

Ok, that was easy...Open manager.js file (in ur extension folder) and change 'switch-panels' and 'switch-group' with each other (line no 60 & 66).

**Comment by vjjustin** [comment]
Well, I am 'that' user on extensions.gnome.org :)
I came here to open it as a feature request. I am so happy to know that u r working on this and the preferences window. Thank you! 

(Ideally, we also need to modify the alt+tab behaviour. As there is no point in rotating through all the windows when we have windows grouped by class. For that, we will have to create a cached 'window_class' list and all new windows have to compared with that list to make sure that class is not already in the cache. But this will make it more complicated and I am busy right now)

**Comment by p91paul** [comment]
This project is moving here https://github.com/dmo60/CoverflowAltTab/ . A newer version has been uploaded to extensions.gnome.org and this bug is solved! thanks for the report.
