### ISSUE TITLE
Activities active in windows switching mode

### ISSUE THREAD

**Issue by KEIII** [p91paul/gnome-shell-extensions-coverflowalttab#13]
Activate windows switching mode by Alt+Tab and during Alt button you can press Activities button and hot corner also active.
I think it is wrong behavior.

Thanks.

**Comment by p91paul** [comment]
Confirmed, it is wrong. Thanks for the report :)

**Comment by p91paul** [comment]
this project is closing. development will continue in another repo, and this issue has been moved there https://github.com/dmo60/CoverflowAltTab/issues/3
