### ISSUE TITLE
Please fix the memory leak.

### ISSUE THREAD

**Issue by TamaraWijsman** [p91paul/gnome-shell-extensions-coverflowalttab#14]
Gnome Shell uses about double the amount of memory it uses without this shell extension.

**How to reproduce:** Hit alt tab a few times, releasing alt each time.

Doing it a 100 times or so it's easy to get the Gnome Shell process over 1 GB in usage.

Thanks in advance...

**Comment by p91paul** [comment]
This seems to be an issue only in gnome-shell 3.6, please confirm you are using that version. No idea on how to fix it, I'll work on it, but this is an hard issue.

**Comment by TamaraWijsman** [comment]
Correct, perhaps this is related to the typical memory leak that can be observed, although a small one compared to this.

gnome-base/gnome-shell
Available versions:  (~)3.2.2.1 (~)3.4.1 (~)3.4.2 *_3.6.1-r1 [1] *_9999 [1] {{+bluetooth +networkmanager systemd}}
Installed versions:  3.6.1-r1 [1](05:48:52 PM 10/30/2012)(networkmanager -bluetooth -i18n -systemd)

**Comment by p91paul** [comment]
I'm closing this repository, since development is going on https://github.com/dmo60/CoverflowAltTab. If you continue having this issue, please report it on that repository.
