### ISSUE TITLE
Extension sometimes hangs.

### ISSUE THREAD

**Issue by johnnynoone** [p91paul/gnome-shell-extensions-coverflowalttab#15]
Occasionally extension will hang and GS has to be restarted. It seems like GS is working, but is unusable, because still image (last frame of animation before crash) covers everything except top panel.

Other people are also experiencing it, see comments on extensions.gnome.org.

Ubuntu 12.04 with stock GS, Nvidia proprietary drivers 304.64.

**Comment by p91paul** [comment]
I saw comments about such issues, however, I cannot reproduce them. Please try to find a deterministic way to obtain this behaviour!

**Comment by p91paul** [comment]
This project is moving here https://github.com/dmo60/CoverflowAltTab/ . A newer version has been uploaded to extensions.gnome.org; if you continue to suffer this bug, please report to the new repository! thanks
