### ISSUE TITLE
X restarts

### ISSUE THREAD

**Issue by svanschu** [p91paul/gnome-shell-extensions-coverflowalttab#17]
After each x  ALT-Tabs the app crashes and with it the whole desktop. It has a lot of HDD IO and restarts gnome automatic.

Willing to give all information which can help ...

Fedora Release 17 (BeefyMiracle) 64-bit
Kernel Linux 3.6.7-4.fc17.x86_64
GNOME 3.4.2

Installed Extensions
Coverflow Alt-Tab 
Dash to Dock
Journal
Panel Settings
Quit Button 
Remove Accessibility
SettingsCenter
Touchpad 
shellshape 
system-monitor

**Comment by p91paul** [comment]
This project is moving here https://github.com/dmo60/CoverflowAltTab/ . A newer version has been uploaded to extensions.gnome.org; if you continue to suffer this bug, please report to the new repository! I'm not reporting, since I cannot reproduce this behaviour. thanks
