### ISSUE TITLE
Usability issue on multi-monitor setup

### ISSUE THREAD

**Issue by slosd** [p91paul/gnome-shell-extensions-coverflowalttab#4]
I have two monitors (my laptop display and a second display). The Animation always happens on the first display and cycles through all windows. 

I suggest to do one of these two things:
- Show it always on the display that is set as the main display and cycle through all windows. 
- Show it on the display on which the cursor is when ALT+Tab is pressed and only cycle through windows that are on that display.

**Comment by p91paul** [comment]
Can you indicate me a similar extension that work as you want, please? I've understood, but with this informations it's easier to fix

**Comment by slosd** [comment]
I'm sorry, I don't know any extension that implements that behaviour. I'm not sure if gTile displays the grid for window placement on the display, the mouse is on. You could give it a try.

**Comment by mgoeppner** [comment]
+1 for this issue. On my triple monitor setup, the extension displays on my left monitor, when my center monitor is the primary display.

**Comment by p91paul** [comment]
@mgoeppner: same question I asked to slosd; have you found any extension working as you want?

**Comment by p91paul** [comment]
This issue should be fixed with last version on extensions.gnome.org. I'm closing this repository, since development is going on https://github.com/dmo60/CoverflowAltTab. If you continue having this issue, please report it on that repository.
